import reflex as rx

def setup_modal() -> rx.Component:
    return rx.fragment(
        rx.box(
            rx.box(
                rx.box(
                    rx.heading(
                        "FiCast Fantasy Podcast",
                        font_weight="800",
                        font_size="3.75rem",
                        line_height="1",
                        as_="h1",
                    ),
                    rx.heading(
                        "Thoughtful Podcasts Prepared with AI-driven Research for AI Characters",
                        margin_top="2rem",
                        font_size="1.25rem",
                        line_height="1.75rem",
                        as_="h2",
                    ),
                    rx.text(
                        "Instructions: Select at least one host and one guest.",
                        font_style="italic",
                        margin_top="1rem",
                        font_size="1.125rem",
                        line_height="1.75rem",
                    ),
                    text_align="center",
                ),
                rx.box(
                    rx.heading(
                        "Hosts",
                        font_weight="700",
                        margin_bottom="1rem",
                        margin_top="2rem",
                        font_size="1.25rem",
                        line_height="1.75rem",
                        as_="h2",
                    ),
                    rx.box(
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/m9ywqcs/Joe-Rogan.png",
                                    alt="Joe Rogan",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Joe Rogan", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/HFZ6VvW/Andrew-Huberman.png",
                                    alt="Andrew Huberman",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Andrew Huberman", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/MPJWNZQ/Sam-Harris-Cartoon.png",
                                    alt="Sam Harris",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Sam Harris", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        gap="2rem",
                        display="grid",
                        grid_template_columns="repeat(3, minmax(0, 1fr))",
                        margin_bottom="2rem",
                    ),
                    rx.heading(
                        "Guests",
                        font_weight="700",
                        margin_bottom="1rem",
                        margin_top="2rem",
                        font_size="1.25rem",
                        line_height="1.75rem",
                        as_="h2",
                    ),
                    rx.box(
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/QjGtucx4kAKBPxi4UwAOTTVteSJmezbq40k7NDwo5w16jjDTA/ComfyUI_00002_.png",
                                    alt="Harry Potter",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Harry Potter", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/t2T7oFjCUcbgOpFplfckt3Tb7fOvQ0f88clfEwPXNOMvyUOMB/ComfyUI_00002_.png",
                                    alt="Iron Man",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Iron Man", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/CEBtzXHIOT7VDtPHeBXwAJDlcwcZ4cM42tuJ4A7zTMP1zxhJA/ComfyUI_00002_.png",
                                    alt="Darth Vader",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Darth Vader", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/eboohJoDnOTvJ62MOZzsVnNJJDyOAe1cp4mYwlcQ2nxHPlDTA/ComfyUI_00002_.png",
                                    alt="Alan Turing",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Alan Turing", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/BtneAyluBHUPHqZ9NFauyH5P65Fkwuf3LbvAUjfZ0be9HVOMB/ComfyUI_00002_.png",
                                    alt="Albert Einstein",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Albert Einstein", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/ZtJM15tz4n6nGpZkZ2bi6yLTfi4MGE3emyLHAUXir1JoUlDTA/ComfyUI_00002_.png",
                                    alt="Genghis Khan",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Genghis Khan", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/zxT3wXAdPE6rNJP1sfroJiTawHskstDIJyX2ufD4fXaw8LHmA/ComfyUI_00002_.png",
                                    alt="Elon Musk",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Elon Musk", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/4Mw6Htt/Jensen-Huang.png",
                                    alt="Jensen Huang",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Jensen Huang", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/eN4pHz2D49XAYqPxnaFcZolYxGzEcdlmpBk5cen8Ib7fFMHmA/ComfyUI_00002_.png",
                                    alt="Gordon Ramsay",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Gordon Ramsay", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/hmY3sd8/pikaso-texttoimage-Cartoon-closeup-portrait-of-presidential-candidate-removebg-preview-transformed.png",
                                    alt="Kamala Harris",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Kamala Harris", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://replicate.delivery/pbxt/EwtmumDFmBoxMB6vF207UslR2vZmHoLUPnWffBkizfGXYPHmA/ComfyUI_00002_.png",
                                    alt="Donald Trump",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Donald Trump", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/PTHQ7Qn/modi-indianprimeminister-removebg.png",
                                    alt="Narendra Modi",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Narendra Modi", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/qymPbXp/Angela-Markel.png",
                                    alt="Angela Markel",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Angela Markel", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/wJR6HTJ/Megan-Thee-Stallion.png",
                                    alt="Megan Jovon Ruth Pete (Megan Thee Stallion)",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Megan Jovon Ruth Pete (Megan Thee Stallion)",
                                font_size="0.75rem",
                                line_height="1rem",
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://i.ibb.co/p0mydmw/Neil-Tyson.png",
                                    alt="Neil deGrasse Tyson",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Neil deGrasse Tyson",
                                font_size="0.75rem",
                                line_height="1rem",
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        gap="2rem",
                        display="grid",
                        grid_template_columns="repeat(3, minmax(0, 1fr))",
                    ),
                    rx.heading(
                        "Custom Participant",
                        font_weight="700",
                        margin_bottom="1rem",
                        margin_top="2rem",
                        font_size="1.25rem",
                        line_height="1.75rem",
                        as_="h2",
                    ),
                    rx.flex(
                        rx.el.button(
                            rx.flex(
                                rx.image(
                                    src="https://www.shutterstock.com/image-vector/user-profile-icon-vector-avatar-600nw-2220431045.jpg",
                                    alt="Custom",
                                    max_width="100%",
                                    max_height="100%",
                                    object_fit="contain",
                                    border_radius="0.5rem",
                                ),
                                display="flex",
                                height="10rem",
                                align_items="center",
                                justify_content="center",
                                width="10rem",
                            ),
                            rx.el.br(),
                            rx.text.span(
                                "Custom Character", font_size="0.75rem", line_height="1rem"
                            ),
                            class_name="dark:border-purple-700",
                            background_color="transparent",
                            border_width="2px",
                            border_color="#1E3A8A",
                            border_style="solid",
                            display="flex",
                            flex_direction="column",
                            align_items="center",
                            justify_content="center",
                            padding="0.75rem",
                            border_radius="1rem",
                        ),
                        display="flex",
                        flex_direction="column",
                        align_items="center",
                        margin_bottom="2rem",
                    ),
                    rx.box(
                        rx.heading(
                            "Number of Rounds",
                            font_weight="600",
                            margin_bottom="0.5rem",
                            font_size="1.125rem",
                            line_height="1.75rem",
                            as_="h2",
                        ),
                        rx.el.select(
                            rx.el.option(
                                "5",
                                value="5",
                                background_color="hsl(245, 20%, 20%)",
                                color="hsl(245, 30%, 90%)",
                            ),
                            rx.el.option(
                                "10",
                                value="10",
                                selected=True,
                                background_color="hsl(245, 20%, 20%)",
                                color="hsl(245, 30%, 90%)",
                            ),
                            rx.el.option(
                                "50",
                                value="50",
                                background_color="hsl(245, 20%, 20%)",
                                color="hsl(245, 30%, 90%)",
                            ),
                            rx.el.option(
                                "100",
                                value="100",
                                background_color="hsl(245, 20%, 20%)",
                                color="hsl(245, 30%, 90%)",
                            ),
                            rx.el.option(
                                "200",
                                value="200",
                                background_color="hsl(245, 20%, 20%)",
                                color="hsl(245, 30%, 90%)",
                            ),
                            color="#ffffff",
                            background_color="hsl(245, 20%, 20%)",
                            background_color="transparent",
                            border_width="1px",
                            border_color="#6B7280",
                            _focus={
                                "outline-style": "none",
                                "box-shadow": "var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color)",
                                "--ring-color": "#8B5CF6",
                            },
                            padding_left="0.75rem",
                            padding_right="0.75rem",
                            padding_top="0.5rem",
                            padding_bottom="0.5rem",
                            border_radius="0.25rem",
                        ),
                        margin_top="1rem",
                    ),
                    text_align="center",
                ),
                rx.box(
                    rx.heading(
                        "Choose your topic",
                        font_size="1.25rem",
                        line_height="1.75rem",
                        as_="h2",
                    ),
                    rx.el.input(
                        class_name="bg-background border-border placeholder-gray-500 text-foreground",
                        placeholder="Enter an interesting topic",
                        value=True,
                        spellcheck="false",
                        custom_attrs={"data-ms-editor": "true"},
                        border_bottom_width="1px",
                        _focus={"border-bottom-width": "2px", "outline-style": "none"},
                        margin_top="0.5rem",
                        padding_left="1rem",
                        padding_right="1rem",
                        padding_top="0.5rem",
                        padding_bottom="0.5rem",
                        font_size="1.125rem",
                        line_height="1.75rem",
                    ),
                    margin_bottom="2rem",
                    margin_top="2rem",
                    text_align="center",
                ),
                rx.box(
                    rx.heading(
                        "Select Musical Style",
                        font_size="1.25rem",
                        line_height="1.75rem",
                        as_="h2",
                    ),
                    rx.el.select(
                        rx.el.option("None", value="None", selected=True),
                        rx.el.option("Ambient", value="Ambient"),
                        rx.el.option("Classical", value="Classical"),
                        rx.el.option("Cinematic", value="Cinematic"),
                        rx.el.option("Electronic", value="Electronic"),
                        rx.el.option("Folk", value="Folk"),
                        rx.el.option("Funk", value="Funk"),
                        rx.el.option("Hip-Hop", value="Hip-Hop"),
                        rx.el.option("Jazz", value="Jazz"),
                        rx.el.option("Pop", value="Pop"),
                        rx.el.option("Rock", value="Rock"),
                        rx.el.option("Soul", value="Soul"),
                        rx.el.option("Blues", value="Blues"),
                        rx.el.option("Country", value="Country"),
                        rx.el.option("Reggae", value="Reggae"),
                        rx.el.option("Latin", value="Latin"),
                        rx.el.option("Metal", value="Metal"),
                        rx.el.option("Dance", value="Dance"),
                        rx.el.option("Chill", value="Chill"),
                        rx.el.option("Acoustic", value="Acoustic"),
                        rx.el.option("Instrumental", value="Instrumental"),
                        rx.el.option("Lo-fi", value="Lo-fi"),
                        rx.el.option("Happy", value="Happy"),
                        rx.el.option("Sad", value="Sad"),
                        rx.el.option("Relaxing", value="Relaxing"),
                        rx.el.option("Upbeat", value="Upbeat"),
                        rx.el.option("Motivational", value="Motivational"),
                        rx.el.option("Funny", value="Funny"),
                        rx.el.option("Dramatic", value="Dramatic"),
                        rx.el.option("Romantic", value="Romantic"),
                        rx.el.option("Horror", value="Horror"),
                        rx.el.option("Epic", value="Epic"),
                        rx.el.option("Corporate", value="Corporate"),
                        rx.el.option("Kids", value="Kids"),
                        rx.el.option("Holiday", value="Holiday"),
                        rx.el.option("Sound Effects", value="Sound Effects"),
                        rx.el.option("Nature", value="Nature"),
                        rx.el.option("Space", value="Space"),
                        rx.el.option("Sci-fi", value="Sci-fi"),
                        rx.el.option("Fantasy", value="Fantasy"),
                        rx.el.option("Historical", value="Historical"),
                        rx.el.option("Adventure", value="Adventure"),
                        rx.el.option("Action", value="Action"),
                        rx.el.option("Mystery", value="Mystery"),
                        rx.el.option("Suspense", value="Suspense"),
                        rx.el.option("Thriller", value="Thriller"),
                        rx.el.option("Comedy", value="Comedy"),
                        rx.el.option("Documentary", value="Documentary"),
                        rx.el.option("Travel", value="Travel"),
                        rx.el.option("Sports", value="Sports"),
                        rx.el.option("News", value="News"),
                        rx.el.option("Games", value="Games"),
                        rx.el.option("Workout", value="Workout"),
                        rx.el.option("Meditation", value="Meditation"),
                        rx.el.option("Study", value="Study"),
                        rx.el.option("Sleep", value="Sleep"),
                        rx.el.option("Background", value="Background"),
                        rx.el.option("Wedding", value="Wedding"),
                        rx.el.option("Party", value="Party"),
                        class_name="Landing_styledSelect__4Y9UM",
                        margin_top="0.5rem",
                    ),
                    margin_bottom="2rem",
                    margin_top="2rem",
                    text_align="center",
                ),
                rx.el.button(
                    "Compose Podcast",
                    class_name="Landing_buttonPrimary__Xl89G Landing_cursorPointer__tarKk",
                    margin_bottom="1rem",
                    position="relative",
                ),
                rx.flex(
                    rx.divider(
                        border_color="#D1D5DB", border_top_width="1px", flex_grow="1"
                    ),
                    rx.text.span(
                        "or", margin_left="0.5rem", margin_right="0.5rem", color="#6B7280"
                    ),
                    rx.divider(
                        border_color="#D1D5DB", border_top_width="1px", flex_grow="1"
                    ),
                    display="flex",
                    align_items="center",
                    margin_top="1rem",
                    margin_bottom="1rem",
                ),
                rx.box(
                    rx.el.button(
                        "Show Sample Podcast",
                        background_color="#6D28D9",
                        font_weight="600",
                        _hover={"background-color": "#8B5CF6"},
                        padding_left="1rem",
                        padding_right="1rem",
                        padding_top="0.5rem",
                        padding_bottom="0.5rem",
                        border_radius="0.25rem",
                        color="#ffffff",
                    ),
                    margin_top="1rem",
                ),
                max_width="768px",
                margin_left="auto",
                margin_right="auto",
                padding="1rem",
                text_align="center",
            )
        )
    )    